apiVersion: apps/v1
kind: Deployment
metadata:
  name: dreiahitm-medt
  namespace: student-m-puchner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dreiahitm-medt
  template:
    metadata:
      labels:
        app: dreiahitm-medt
    spec:
      containers:
        - name: dreiahitm-medt
          image: ghcr.io/manuelpuchner/3ahitm-medt-frontend:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: dreiahitm-medt-svc
  namespace: student-m-puchner
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: dreiahitm-medt
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dreiahitm-medt
  namespace: student-m-puchner
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: student.cloud.htl-leonding.ac.at
      http:
        paths:
          - path: /m.puchner/htlife(.*)
            pathType: Prefix
            backend:
              service:
                name: dreiahitm-medt-svc
                port:
                  number: 80